# Generated by Django 4.2.7 on 2023-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0002_testinglogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinglogs",
            name="type",
            field=models.CharField(default="SENT", max_length=50),
            preserve_default=False,
        ),
    ]
