# Generated by Django 4.2.7 on 2023-11-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0003_testinglogs_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="contact_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="cycle",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="subscription_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="title",
        ),
        migrations.AddField(
            model_name="invoice",
            name="contact_email",
            field=models.EmailField(default="placeholder", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="contact_name",
            field=models.TextField(default="placeholder"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="contact_phone_number",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student_email",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="preview_link",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INVOICE_SENT", "INVOICE_SENT"),
                            ("INVOICE_PAID", "INVOICE_PAID"),
                            ("INVOICE_OVERDUE", "INVOICE_OVERDUE"),
                            ("EMAIL_SENT", "EMAIL_SENT"),
                            ("EMAIL_OPENED", "EMAIL_OPENED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("error", models.BooleanField(default=False)),
                ("error_message", models.TextField(null=True)),
                ("json_data", models.TextField(null=True)),
                (
                    "associated_email",
                    models.ForeignKey(
                        null=True, on_delete=models.SET("deleted"), to="wix_app.email"
                    ),
                ),
                (
                    "associated_invoice",
                    models.ForeignKey(
                        on_delete=models.SET("deleted"), to="wix_app.invoice"
                    ),
                ),
            ],
        ),
    ]
