# Generated by Django 4.2.7 on 2023-11-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0004_remove_invoice_contact_id_remove_invoice_cycle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="assosciated_invoice_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="eventlog",
            name="associated_invoice",
            field=models.ForeignKey(
                null=True, on_delete=models.SET("deleted"), to="wix_app.invoice"
            ),
        ),
    ]
