# Generated by Django 4.2.7 on 2023-11-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0005_eventlog_assosciated_invoice_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="error_type",
            field=models.CharField(default="default", max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventlog",
            name="note",
            field=models.TextField(null=True),
        ),
    ]
