# Generated by Django 4.2.7 on 2023-11-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0006_eventlog_error_type_eventlog_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("FULLY_PAID", "FULLY_PAID"),
                    ("PENDING", "PENDING"),
                    ("OVERDUE", "OVERDUE"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                default="PENDING",
            ),
            preserve_default=False,
        ),
    ]
