# Generated by Django 4.2.7 on 2023-11-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0007_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="line_number",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "PAID"),
                    ("PENDING", "PENDING"),
                    ("OVERDUE", "OVERDUE"),
                    ("SUSPENDED", "SUSPENDED"),
                ]
            ),
        ),
    ]
