# Generated by Django 4.2.7 on 2023-11-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0008_eventlog_line_number_alter_invoice_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventlog",
            old_name="assosciated_invoice_id",
            new_name="associated_invoice_number",
        ),
    ]
