# Generated by Django 4.2.7 on 2023-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wix_app",
            "0009_rename_assosciated_invoice_id_eventlog_associated_invoice_number",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="offenses",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
