# Generated by Django 4.2.7 on 2023-11-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0010_invoice_offenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="product_name",
            field=models.TextField(default="Team Tomorrow Guided Internship"),
            preserve_default=False,
        ),
    ]
