# Generated by Django 4.2.7 on 2023-11-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0011_invoice_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationLogs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("json_data", models.TextField()),
            ],
        ),
    ]
