# Generated by Django 4.2.7 on 2023-11-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0012_cancellationlogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="line_number",
            field=models.IntegerField(default=-1),
        ),
    ]
