# Generated by Django 4.2.7 on 2023-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wix_app", "0014_ping_alter_eventlog_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ping",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
